name: Deployment Clodflare Pages Production

on:
  pull_request:
    branches:
      - master

jobs:
  deployment:
    environment:
      name: Production
      url: https://www.rasio.dev
    runs-on: ubuntu-latest
    name: Deploy Clodflare Pages
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install Dependencies
        run: |
          npm install
      - name: Build Astro
        run: |
          npm run build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: 'pages deploy ${{ vars.CLOUDFLARE_PAGES_DIST_DIRECTORY }} --project-name=${{ vars.CLOUDFLARE_PAGES_PROJECT_NAME }} --branch=${{ vars.CLOUDFLARE_PAGES_TARGET_BRANCH }}'